'use strict';
const $=id=>document.getElementById(id);const KEY='vygodno-draft-v1';const U={'г':['mass',1,'кг',1000],'кг':['mass',1000,'кг',1000],'мл':['volume',1,'л',1000],'л':['volume',1000,'л',1000],'шт':['piece',1,'шт',1]};
let items=[],images=new Map(),nextId=1,pendingPhoto=null,ocrWorker=null;
const fmt=x=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2,minimumFractionDigits:2}).format(x);
const parse=x=>{const n=Number(String(x).replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:NaN};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const per=x=>x.price/(x.qty*U[x.unit][1])*U[x.unit][3];
const type=x=>U[x.unit][0];
const unitName=x=>U[x.unit][2];
function save(){localStorage.setItem(KEY,JSON.stringify(items.map(({id,name,qty,unit,price,regular,promo,characteristics,source,ack})=>({id,name,qty,unit,price,regular,promo,characteristics,source,ack}))));}
try{let arr=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(arr))items=arr.filter(x=>x&&U[x.unit]&&x.qty>0&&x.price>0).slice(0,5);nextId=Math.max(0,...items.map(x=>x.id||0))+1;}catch{}
function addItem(obj){if(items.length>=5)return false;items.push({id:nextId++,name:'',characteristics:'',regular:null,promo:null,source:'manual',ack:false,...obj});save();render();return true;}

const ROW_KEY='vygodno-manual-rows-v2';
let manualRows=[];
try{const saved=JSON.parse(localStorage.getItem(ROW_KEY)||'null');if(Array.isArray(saved))manualRows=saved.filter(x=>x&&typeof x==='object').slice(0,5).map(x=>({rowId:Number(x.rowId)||0,id:x.id||null,qty:String(x.qty??''),unit:U[x.unit]?x.unit:'г',price:String(x.price??'')}));}catch{}
if(!manualRows.length)manualRows=items.filter(x=>x.source!=='photo').map(x=>({rowId:x.id,id:x.id,qty:String(x.qty),unit:x.unit,price:String(x.price)}));
let nextRowId=Math.max(0,...manualRows.map(x=>x.rowId||0))+1;
while(manualRows.length<2&&manualRows.length+items.filter(x=>x.source==='photo').length<5)manualRows.push({rowId:nextRowId++,id:null,qty:'',unit:'г',price:''});
function saveManual(){localStorage.setItem(ROW_KEY,JSON.stringify(manualRows));}
function warn(message){$('entryError').textContent=message;$('entryError').classList.remove('hidden');}
function hideWarn(){$('entryError').classList.add('hidden')}
function renderManual(){
  const photos=items.filter(x=>x.source==='photo').length;
  const slots=5-photos;
  manualRows=manualRows.slice(0,slots);
  $('manualRows').innerHTML=manualRows.map((r,i)=>`<div class="manual-entry" data-row="${r.rowId}"><div class="manual-head"><strong>Товар №${i+1}</strong>${manualRows.length>2?'<button class="smallbtn dangertext" data-remove-row="'+r.rowId+'">Удалить</button>':''}</div><div class="formgrid"><div><label>Вес / объём</label><input data-field="qty" inputmode="decimal" placeholder="900" value="${esc(r.qty)}"></div><div><label>Ед.</label><select data-field="unit">${Object.keys(U).map(u=>`<option value="${u}" ${r.unit===u?'selected':''}>${u}</option>`).join('')}</select></div><div><label>Цена, ₽</label><input data-field="price" inputmode="decimal" placeholder="109,90" value="${esc(r.price)}"></div></div></div>`).join('');
  $('manualRows').querySelectorAll('[data-row]').forEach(el=>{
    const row=manualRows.find(r=>r.rowId===Number(el.dataset.row));
    el.querySelectorAll('[data-field]').forEach(input=>input.addEventListener(input.tagName==='SELECT'?'change':'input',()=>{
      row[input.dataset.field]=input.value;hideWarn();syncManualRow(row);
    }));
  });
  $('manualRows').querySelectorAll('[data-remove-row]').forEach(b=>b.onclick=()=>{
    const row=manualRows.find(x=>x.rowId===Number(b.dataset.removeRow));
    if(row.id){items=items.filter(x=>x.id!==row.id);images.delete(row.id);}
    manualRows=manualRows.filter(x=>x!==row);save();saveManual();renderManual();render();
  });
  $('add').disabled=manualRows.length+photos>=5;
  $('capacity').textContent=`${manualRows.length+photos} из 5`;
  saveManual();
}
function syncManualRow(row){
  const qty=parse(row.qty),price=parse(row.price);
  const old=items.find(x=>x.id===row.id);
  if(qty>0&&price>0){
    if(old)Object.assign(old,{qty,price,unit:row.unit});
    else if(items.length<5){const id=nextId++;items.push({id,name:'',characteristics:'',regular:null,promo:null,source:'manual',ack:false,qty,unit:row.unit,price});row.id=id;}
  }else if(old){items=items.filter(x=>x.id!==old.id);row.id=null;}
  save();saveManual();render();
}
$('add').onclick=()=>{
  hideWarn();
  if(manualRows.length+items.filter(x=>x.source==='photo').length>=5)return warn('Максимум 5 товаров.');
  manualRows.push({rowId:nextRowId++,id:null,qty:'',unit:manualRows.at(-1)?.unit||'г',price:''});
  renderManual();
  $('manualRows').lastElementChild?.querySelector('[data-field="qty"]')?.focus();
};
$('clear').onclick=()=>{
  if(!items.length||confirm('Очистить все товары и начать новое сравнение?')){
    items=[];images.clear();pendingPhoto=null;manualRows=[];
    while(manualRows.length<2)manualRows.push({rowId:nextRowId++,id:null,qty:'',unit:'г',price:''});
    save();saveManual();renderManual();render();$('ocrReview').classList.add('hidden');$('ocrStatus').textContent='Один снимок — один ценник.';
  }
};
function differences(a,b){let result=[];if(a.source==='photo'&&b.source==='photo'&&a.name&&b.name){let aa=a.name.toLowerCase(),bb=b.name.toLowerCase();const patterns=[['жирность',/(\d{1,2}[,.]\d)\s*%/],['массовая доля',/(\d{2}[,.]\d)\s*%/]];for(let [label,re] of patterns){let m1=aa.match(re),m2=bb.match(re);if(m1&&m2&&m1[1]!==m2[1]){result.push(`Возможное отличие (${label}): ${m1[1]}% и ${m2[1]}%`);break}}const groups=[['молоко','кефир','сливки','йогурт'],['масло','спред','маргарин'],['растворим','молот']];for(const group of groups){const a1=group.find(w=>aa.includes(w)),b1=group.find(w=>bb.includes(w));if(a1&&b1&&a1!==b1)result.push(`Разные типы продукта: «${a1}» и «${b1}»`);} }return result;}
function render(){const container=$('products');$('count').textContent=`${items.length} из 5`;$('takePhoto').disabled=$('pickPhoto').disabled=items.length>=5;
const same=items.length>0&&items.every(x=>type(x)===type(items[0]));const best=same&&items.length>=2?items.reduce((a,b)=>per(a)<=per(b)?a:b):null;let html='';items.forEach((p,i)=>{let issues=items.filter(x=>x.id!==p.id).flatMap(x=>differences(p,x));let hasUnknown=p.source==='photo'&&!p.characteristics&&!/%|безлактоз|пастериз|ультрапастериз/i.test(p.name);let photo=images.get(p.id);html+=`<div class="product ${best?.id===p.id?'best':''}"><div class="row"><h3>${esc(p.name||`Товар №${i+1}`)} ${best?.id===p.id?'<span class="chip">Выгоднее</span>':''}</h3><button class="smallbtn dangertext" data-delete="${p.id}">Удалить</button></div><div class="row" style="margin-top:9px"><div>${fmt(p.qty)} ${esc(p.unit)} · <b>${fmt(p.price)} ₽</b><div class="muted">${p.regular!=null&&p.promo!=null?`Обычная ${fmt(p.regular)} ₽ · по карте ${fmt(p.promo)} ₽`:''}</div></div><div class="unitprice">${fmt(per(p))} ₽/${unitName(p)}</div></div><div class="row" style="margin-top:8px"><div>${photo?`<img class="photo" alt="Фото ценника" src="${photo}" data-photo="${p.id}">`:''}</div><button class="smallbtn" data-edit="${p.id}">✎ Изменить</button></div><div class="editor hidden" id="edit-${p.id}"></div>${issues.length&&!p.ack?`<div class="notice">⚠ ${esc([...new Set(issues)].join('; '))}. Товары могут различаться.<div class="row"><button class="smallbtn" data-accept="${p.id}">Всё равно сравнить</button><button class="smallbtn dangertext" data-delete="${p.id}">Убрать товар</button></div></div>`:''}${hasUnknown?'<div class="note">Характеристики могут быть неполными. При необходимости добавь их в «Изменить».</div>':''}</div>`});container.innerHTML=html||'<p>Добавь первый товар вручную или по фото.</p>';
items.forEach(p=>{const target=$(`edit-${p.id}`);target.innerHTML=`<div class="stack"><div><label>Название (необязательно)</label><input data-field="name" value="${esc(p.name)}"></div><div><label>Характеристики (можно указать вручную)</label><input data-field="characteristics" placeholder="Например, жирность 2,5%" value="${esc(p.characteristics)}"></div><div class="formgrid"><div><label>Количество</label><input data-field="qty" inputmode="decimal" value="${p.qty}"></div><div><label>Единица</label><select data-field="unit">${Object.keys(U).map(x=>`<option value="${x}" ${x===p.unit?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Цена, ₽</label><input data-field="price" inputmode="decimal" value="${p.price}"></div></div>${p.regular!=null&&p.promo!=null?`<div class="actions"><button class="btn secondary" data-price="regular">Обычная ${fmt(p.regular)} ₽</button><button class="btn secondary" data-price="promo">По карте ${fmt(p.promo)} ₽</button></div>`:''}<button class="btn" data-save="${p.id}">Сохранить изменения</button><div class="notice hidden" id="error-${p.id}"></div></div>`;target.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{target.querySelector('[data-field="price"]').value=p[b.dataset.price]});target.querySelector('[data-save]').onclick=()=>{const get=f=>target.querySelector(`[data-field="${f}"]`).value;const qty=parse(get('qty')),price=parse(get('price'));if(!(qty>0&&price>0)){$(`error-${p.id}`).textContent='Вес и цена должны быть положительными';$(`error-${p.id}`).classList.remove('hidden');return;}Object.assign(p,{name:get('name'),characteristics:get('characteristics'),qty,price,unit:get('unit'),ack:false});save();render()};});
container.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{let e=$(`edit-${b.dataset.edit}`);e.classList.toggle('hidden')});container.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{items=items.filter(x=>x.id!==Number(b.dataset.delete));images.delete(Number(b.dataset.delete));manualRows.forEach(r=>{if(r.id===Number(b.dataset.delete)){r.id=null;r.qty='';r.price='';}});save();saveManual();renderManual();render()});container.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{let p=items.find(x=>x.id===Number(b.dataset.accept));p.ack=true;save();render()});container.querySelectorAll('[data-photo]').forEach(img=>img.onclick=()=>{$('modalImage').src=img.src;$('modal').classList.add('show')});
const r=$('result');if(!items.length)r.innerHTML='';else if(!same)r.innerHTML='<div class="notice">⚠ Массу, объём и штуки нельзя сравнивать между собой. Измени единицы или убери несопоставимый товар.</div>';else if(items.length===1)r.innerHTML=`<div class="success">Стоимость одного товара: <strong>${fmt(per(items[0]))} ₽/${unitName(items[0])}</strong>. Добавь второй для сравнения.</div>`;else {const costly=items.reduce((a,b)=>per(a)>=per(b)?a:b);const saving=(1-per(best)/per(costly))*100;r.innerHTML=`<div class="success"><b>✓ Самый выгодный — ${esc(best.name||`Товар №${items.indexOf(best)+1}`)}</b><br>Цена: ${fmt(per(best))} ₽/${unitName(best)}<br>Экономия до <b>${fmt(saving)}%</b> относительно самого дорогого варианта за единицу.</div>`;}$('shareButtons').classList.toggle('hidden',items.length===0);}
$('closeModal').onclick=()=>$('modal').classList.remove('show');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('show')};
$('takePhoto').onclick=()=>$('cameraInput').click();$('pickPhoto').onclick=()=>$('galleryInput').click();$('cameraInput').onchange=$('galleryInput').onchange=e=>{let file=e.target.files[0];if(file)recognizePhoto(file);e.target.value=''};
async function loadOCR(){if(!window.Tesseract){$('ocrStatus').textContent='Загружаю бесплатную OCR-библиотеку…';await new Promise((ok,fail)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}if(!ocrWorker){$('ocrStatus').textContent='Загружаю русский и английский языки…';ocrWorker=await Tesseract.createWorker('rus+eng',1,{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`Распознаю текст: ${Math.round((m.progress||0)*100)}%`}})}return ocrWorker;}
function extract(raw){const text=raw.replace(/\u00a0/g,' '),lower=text.toLowerCase();const candidates=[...text.matchAll(/(\d{1,4}(?:[\s,.]\d{1,2})?)\s*(?:₽|руб\.?|р\b)/gi)].map(m=>parse(m[1])).filter(x=>x>0);const lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean);let prices=candidates.length?candidates:[...text.matchAll(/(?:^|\s)(\d{1,4}[,.]\d{2})(?=\s|$)/gm)].map(m=>parse(m[1])).filter(x=>x>0);prices=[...new Set(prices)].filter(Number.isFinite);const amounts=[...lower.matchAll(/(\d+(?:[,.]\d+)?)\s*(кг|г|мл|л|шт)\b/g)].map(m=>({qty:parse(m[1]),unit:m[2]})).filter(x=>x.qty>0);let chosen=amounts.find(x=>x.unit==='мл'||x.unit==='г')||amounts[0]||null;const knownPrice=prices.length?Math.max(...prices):null,cardPrice=prices.length>1?Math.min(...prices):null;let name=lines.filter(x=>/[а-яa-z]{3}/i.test(x)&&!/(скидк|руб|цена|карта|₽)/i.test(x)).slice(0,2).join(' ').slice(0,100);let printedUnit=null;const uMatch=lower.match(/(?:за\s*1\s*(кг|л)|за\s*100\s*(г|мл))[\s:]*([\d\s,.]+)\s*(?:₽|руб)/);if(uMatch)printedUnit={unit:uMatch[1]||uMatch[2],value:parse(uMatch[3])};return {name,qty:chosen?.qty||'',unit:chosen?.unit||'г',regular:knownPrice||'',promo:cardPrice||'',price:cardPrice||knownPrice||'',raw:text,printedUnit};}
async function recognizePhoto(file){if(items.length>=5)return;let url=URL.createObjectURL(file);pendingPhoto={url};$('ocrReview').classList.add('hidden');try{let worker=await loadOCR();const result=await worker.recognize(file);let d=extract(result.data.text);pendingPhoto={url,data:d};showReview(d);$('ocrStatus').textContent='Проверь распознанные поля. OCR иногда путает цифры, цены и объём.';}catch(err){pendingPhoto={url,data:{name:'',qty:'',unit:'г',price:'',regular:'',promo:'',raw:'',printedUnit:null}};showReview(pendingPhoto.data);$('ocrStatus').textContent='Автораспознавание недоступно: '+(err.message||err)+'. Введи данные с фото вручную.';}}
function showReview(d){$('ocrReview').innerHTML=`<h3 style="margin:0 0 10px">Проверь данные ценника</h3><div class="row"><img class="photo" id="reviewPhoto" alt="Фото ценника" src="${pendingPhoto.url}"><span class="muted">Любое поле можно исправить</span></div><div class="stack" style="margin-top:10px"><div><label>Название (необязательно)</label><input id="rName" value="${esc(d.name)}"></div><div class="editorgrid"><div><label>Обычная цена, ₽</label><input id="rRegular" inputmode="decimal" value="${d.regular}"></div><div><label>Цена по карте, ₽</label><input id="rPromo" inputmode="decimal" value="${d.promo}"></div></div><div class="formgrid"><div><label>Вес / объём</label><input id="rQty" inputmode="decimal" value="${d.qty}"></div><div><label>Единица</label><select id="rUnit">${Object.keys(U).map(x=>`<option ${x===d.unit?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Выбор цены</label><select id="rChoice"><option value="promo" ${d.promo?'':'disabled'}>По карте</option><option value="regular" ${d.promo?'':'selected'}>Обычная</option></select></div></div><div><label>Характеристики (если известны)</label><input id="rCharacteristics" placeholder="Например, жирность 2,5%"></div><div id="rValidation"></div><button class="btn" id="confirmPhoto">Добавить товар</button><button class="btn outline" id="cancelPhoto">Отмена</button><details><summary class="muted">Показать исходный распознанный текст</summary><pre style="white-space:pre-wrap;font-size:12px">${esc(d.raw)}</pre></details></div>`;$('ocrReview').classList.remove('hidden');$('reviewPhoto').onclick=()=>{$('modalImage').src=pendingPhoto.url;$('modal').classList.add('show')};$('rRegular').oninput=$('rPromo').oninput=$('rChoice').onchange=$('rQty').oninput=$('rUnit').onchange=validateReview;$('confirmPhoto').onclick=()=>{const q=parse($('rQty').value),regular=parse($('rRegular').value),promo=parse($('rPromo').value),price=$('rChoice').value==='promo'?promo:regular;if(!(q>0&&price>0)){ $('rValidation').innerHTML='<div class="notice">Проверь количество и выбранную цену.</div>';return;}let id=nextId;addItem({name:$('rName').value,qty:q,unit:$('rUnit').value,price,regular:regular>0?regular:null,promo:promo>0?promo:null,characteristics:$('rCharacteristics').value,source:'photo'});images.set(id,pendingPhoto.url);pendingPhoto=null;renderManual();$('ocrReview').classList.add('hidden');$('ocrStatus').textContent='Товар добавлен. Можно добавить следующий.';render();};$('cancelPhoto').onclick=()=>{URL.revokeObjectURL(pendingPhoto.url);pendingPhoto=null;$('ocrReview').classList.add('hidden')};validateReview();}
function validateReview(){if(!pendingPhoto)return;const d=pendingPhoto.data;let msg=[];let amount=parse($('rQty').value),price=parse($('rChoice').value==='promo'?$('rPromo').value:$('rRegular').value);if(!(amount>0))msg.push('Не определён вес или объём — укажи вручную.');if(!(price>0))msg.push('Не определена выбранная цена — укажи вручную.');if(d.printedUnit&&amount>0&&price>0){let x={qty:amount,unit:$('rUnit').value,price};if(U[x.unit]&&d.printedUnit.unit===unitName(x)){let calculated=per(x);if(Math.abs(calculated-d.printedUnit.value)>Math.max(.1,calculated*.025))msg.push('Цена за единицу на ценнике может не совпадать с расчётом. Проверь данные и вид цены.')}}$('rValidation').innerHTML=msg.map(m=>`<div class="notice">⚠ ${esc(m)}</div>`).join('');}
function shareString(){return 'Сравнение цен — Выгодно?\n'+items.map((p,i)=>`${i+1}. ${p.name||'Товар №'+(i+1)}: ${fmt(p.qty)} ${p.unit}, ${fmt(p.price)} ₽, ${fmt(per(p))} ₽/${unitName(p)}`).join('\n')+'\n'+($('result').textContent||'');}
$('shareText').onclick=async()=>{let text=shareString();try{if(navigator.share)await navigator.share({text});else{await navigator.clipboard.writeText(text);alert('Результат скопирован')}}catch(e){if(e.name!=='AbortError')prompt('Скопируй результат',text)}};
$('shareImage').onclick=async()=>{const c=document.createElement('canvas');c.width=900;c.height=170+items.length*90;const ctx=c.getContext('2d');ctx.fillStyle='#f7faf8';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#176b47';ctx.font='bold 38px system-ui';ctx.fillText('Выгодно? — сравнение цен',36,60);ctx.fillStyle='#142c21';ctx.font='25px system-ui';items.forEach((p,i)=>{ctx.fillText(`${i+1}. ${(p.name||'Товар №'+(i+1)).slice(0,28)} — ${fmt(p.price)} ₽`,38,120+i*90);ctx.fillStyle='#186d4a';ctx.fillText(`${fmt(p.qty)} ${p.unit}   •   ${fmt(per(p))} ₽/${unitName(p)}`,38,153+i*90);ctx.fillStyle='#142c21';});let blob=await new Promise(r=>c.toBlob(r,'image/png'));const f=new File([blob],'sravnenie-cen.png',{type:'image/png'});try{if(navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:'Сравнение цен'});else{let a=document.createElement('a');a.download=f.name;a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}}catch(e){if(e.name!=='AbortError')alert('Не удалось поделиться картинкой')}};
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});renderManual();render();